version: '3.9'

services:
  app:
    image: ${DOCKER_IMAGE}
    ports:
      - ${APP_PORT:-3000}:3000
    volumes:
      - ./:/usr/src/app
    env_file:
      - .env
    command: ["dumb-init", "react-scripts", "build"]
